on:
  pull_request:
    branches:
      - main

permissions:
  # security-events: write 
  contents: read 
  actions: read 

jobs:
  terraform-checks:
    name: 'Terraform Checks'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./abinbev_app
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Format
      run: terraform fmt -check -recursive
    
    # - name: Run Checkov action
    #   id: checkov
    #   uses: bridgecrewio/checkov-action@master
    #   with: 
    #     framework: terraform

    # - name: Upload SARIF file
    #   if: success() || failure()
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: results.sarif
    #     category: checkov